GET http://localhost:8080/secured/status

###

GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZUBib2IuY29tIiwibmJmIjoxNjI4NTQ0Njg2LCJzZXgiOiJNIiwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9OT05VU0VSIl0sImlzcyI6ImF1dGgiLCJleHAiOjE2Mjg1NDgyODYsImxvY2FsZSI6ImVuIiwiaWF0IjoxNjI4NTQ0Njg2fQ.jG9WHnQZFbTy9l4TMp_S_QOLG3Xe4He3KOpfhFDn2_Y
