POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "alice@bob.com",
  "password": "secret"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
"username": "alice@bob.com",
"password": "secret2"
}
