GET http://localhost:8080/secured/status

###

GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZUBib2IuY29tIiwibmJmIjoxNjI4NTQ0MTU5LCJyb2xlcyI6W10sImlzcyI6ImF1dGgiLCJleHAiOjE2Mjg1NDc3NTksImlhdCI6MTYyODU0NDE1OX0._nY6yqxcWBA_aATvPdI32ufrHEYvlZLX_B22q8dStrE
