micronaut:
  application:
    name: mn-fund
  server:
    port: 8082
datasources:
  default:
    url: jdbc:mysql://localhost:13306/mn-fund
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
    schema-generate: NONE
    dialect: MYSQL
liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml'
      drop-first: false
