micronaut:
  application:
    name: demo
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              base64: true
              jws-algorithm: HS256

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:15432/mn-stock`}
      user: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:secret}
      schemas: mn
      default-schema: mn

jackson:
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZobeId: true
    writeDateTimestampsaAsNanoseconds: true
#  generator:
#    writeNumbersAsStrings: true
#    writeBigDecimalAsPlain: true
